### ISSUE TITLE
List Manipulation unable to handle double-nested elements

### ISSUE THREAD

**Issue by jcquinlan** [kylesb/range.js#5]
While range.js can be used to control the display of lists and nested lists, it fails to cover any deeper level of nested elements. I somewhat expected this, so I will outline a potential fix, assuming I am correct in my assumption of what the issue is.

**Theory:** In updateList() I am not recursively exploring this target element, rather I am using hardcoded for loops to search, at most, two layers of the element.

**Potential Fix:** Write a recursive method similar to searchChildren() that will check for child elements, else it will compare the elements data-position to the current range to dictate it's display property. This will prevent placing a limit in the maximum number of nested elements able to be selectively hidden by the associated range input.

**Comment by kylesb** [comment]
Updated with patch [beb151d (https://github.com/kylesb/range.js/commit/beb151d237649679fe89727ce44822bbbe8de759)

**Comment by kylebelanger** [comment]
Fixed with patch: [46affd](https://github.com/kylesb/range.js/commit/b46affdb814a33caf69bb8aa61dbc76634415f07). Can now handle unlimited nested list elements.

**Solution:** The problem was the data-position and input range values were being treated as strings, and not integers. To fix, I simply parse the range value to an integer in the event listener.
